layout: {qmk_keyboard: corne_rotated, qmk_layout: LAYOUT_split_3x6_3}
layers:
  Home:
  - - {t: ESC, h: Extend2}
    - Q
    - W
    - E
    - R
    - T
    - Y
    - U
    - I
    - O
  - - P
    - BSPC
    - {t: TAB, h: Bluetooth}
    - A
    - S
    - D
    - F
    - G
    - H
    - J
  - [K, L, ;, '''', LSHFT, Z, X, C, V, B]
  - - N
    - M
    - ','
    - .
    - /
    - RSHIFT
    - LCTRL
    - LWIN
    - SPACE
    - {t: SPACE, h: Function}
  - [Extend, RALT]
  Function:
  - [ESC, '', '', '', '', '', PAGE UP, UP, PAGE DOWN, '7']
  - ['8', '9', TAB, '', '', '', '', '', LEFT, DOWN]
  - [RIGHT, '4', '5', '6', LSHFT, '', '', '', '', PSCRN]
  - - HOME
    - END
    - '0'
    - '1'
    - '2'
    - '3'
    - LCTRL
    - LWIN
    - SPACE
    - {type: held}
  - - {t: ▽, type: trans}
    - RALT
  Extend:
  - [ESC, '!', '@', '#', $, '%', ^, '&', KP MULTIPLY, (]
  - [), BSPC, TAB, (, ), '[', ']', '', '-', '=']
  - [/, \, '`', '''', LSHFT, <, '>', '{', '}', '']
  - - _
    - +
    - ''
    - '|'
    - '~'
    - RSHIFT
    - LCTRL
    - LWIN
    - SPACE
    - {t: ▽, type: trans}
  - - {type: held}
    - RALT
  Extend2:
  - - {t: ESC, type: held}
    - '!'
    - '@'
    - '#'
    - $
    - '%'
    - ^
    - '&'
    - KP MULTIPLY
    - (
  - [), BSPC, TAB, '~', '', '', '', '', '-', '=']
  - [/, '[', ']', '''', LSHFT, <, '>', \, '`', '|']
  - - _
    - +
    - \
    - '{'
    - '}'
    - RSHIFT
    - LCTRL
    - LWIN
    - SPACE
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - RALT
  Bluetooth:
  - - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - {t: BT, h: '1'}
    - {t: BT, h: '2'}
    - {t: BT, h: '3'}
    - {t: BT, h: '4'}
  - - {t: BT, h: '5'}
    - {t: BT, h: '6'}
    - {type: held}
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
  - ['', '', '', '', '', '', '', '', '', '']
  - ['', '', '', '', '', '', '', '', '', '']
  - ['', '']
  Media:
  - ['', '', '', '', '', '', PREV, PP, NEXT, '']
  - ['', VOL UP, '', '', '', '', '', '', '', '']
  - ['', '', '', MUTE, '', '', '', '', '', '']
  - ['', '', '', '', '', VOL DN, '', '', '', '']
  - ['', '']
combos:
- p: [10, 11]
  k: DELETE
  l: [Home, Extend]
- p: [22, 23]
  k: ENTER
  l: [Home]
- p: [34, 35]
  k: INSERT
  l: [Home]
- p: [24, 25]
  k: '&caps_word'
  l: [Home]
- p: [36, 37]
  k: LEFT ALT
  l: [Home]
- p: [39, 40, 41]
  k: BT CLR
  l: [Extend2]
- p: [13, 14]
  k: LC(A)
  l: [Home]
- p: [26, 27]
  k: LC(X)
  l: [Home]
- p: [27, 28]
  k: LC(C)
  l: [Home]
- p: [28, 29]
  k: LC(V)
  l: [Home]
- p: [0, 1, 2]
  k: LC(Z)
  l: [Home]
- p: [9, 10, 11]
  k: LC(Y)
  l: [Home]
- p: [0, 12]
  k: F1
  l: [Home]
- p: [1, 13]
  k: F2
  l: [Home]
- p: [2, 14]
  k: F3
  l: [Home]
- p: [3, 15]
  k: F4
  l: [Home]
- p: [4, 16]
  k: F5
  l: [Home]
- p: [5, 17]
  k: F6
  l: [Home]
- p: [6, 18]
  k: F7
  l: [Home]
- p: [7, 19]
  k: F8
  l: [Home]
- p: [8, 20]
  k: F9
  l: [Home]
- p: [9, 21]
  k: F10
  l: [Home]
- p: [10, 22]
  k: F11
  l: [Home]
- p: [11, 23]
  k: F12
  l: [Home]
